When LoadStore a uint32, return value should be uint32.
v8-riscv/v8 pull request #222
Opened 2020-09-07 09:25 UTC by luyahan

Fix #215

2020-09-07 09:55 UTC, luyahan commented
fix #215

2020-09-07 15:20 UTC, lazyparser commented on test/cctest/test-assembler-riscv64.cc
hello from PLCT ci bot

2020-09-08 14:14 UTC, penguinwu requested changes
LGTM.

But there are a few other `GenAndRunTest` functions that also have a similar problem of potentially returning int32/64 for uint32/64 input types. Search for string `int32_t, int64_t`. Please separate the floating-point version from the integer version and fix those too.

2020-09-09 00:15 UTC, penguinwu commented
@luyahan Let's put this PR on hold (no need to address my change request). I am finishing up a pretty extensive refactoring PR for `test-assembler/macro-assembler-riscv64.cc` that touches the same `GenAndRunTest` functions that you modified here. I've incorporated the fixes (without duplicating GenAndRunTest functions for floating-point) for all similar cases in my PR. Let me merge my PR first. If the problem still persists, you can apply your fix on top of mine.

2020-09-09 09:03 UTC, luyahan commented
> @luyahan Let's put this PR on hold (no need to address my change request). I am finishing up a pretty extensive refactoring PR for `test-assembler/macro-assembler-riscv64.cc` that touches the same `GenAndRunTest` functions that you modified here. I've incorporated the fixes (without duplicating GenAndRunTest functions for floating-point) for all similar cases in my PR. Let me merge my PR first. If the problem still persists, you can apply your fix on top of mine.

That's the best !

2020-09-10 17:40 UTC, penguinwu commented
@luyahan My PR  is merged. Please try the latest from riscv64 to see if it fixes the problem you reported. If so, please close the corresponding issue.

2020-09-16 01:34 UTC, closed without merging