add RVC instr c.lw, c.ld, c.fld
v8-riscv/v8 pull request #264
Opened 2020-10-06 01:30 UTC by derekztu22

2020-10-06 02:36 UTC, LOGQTAINIA requested changes
Others look good to me.

2020-10-06 02:36 UTC, LOGQTAINIA commented on src/codegen/riscv64/assembler-riscv64.h
> +  void c_fld(FPURegister rd, Register rs1, int16_t imm8);
`int16_t` -> `uint16_t`

`imm7` -> `uimm7`

2020-10-06 02:36 UTC, LOGQTAINIA commented on src/codegen/riscv64/assembler-riscv64.h
> +                  Register rs1, int8_t uimm5);
`int8_t` -> `uint8_t`

2020-10-06 05:03 UTC, LOGQTAINIA requested changes
Keep consistance between declaration and definition

2020-10-06 05:03 UTC, LOGQTAINIA commented on src/codegen/riscv64/assembler-riscv64.cc
> +
the same as declaration.

`int8_t` -> `uint8_t`

2020-10-06 05:03 UTC, LOGQTAINIA commented on src/codegen/riscv64/assembler-riscv64.cc
> +
the same as declaration.

`int16_t` -> `uint16_t`

2020-10-07 00:48 UTC, derekztu22 commented
@penguinwu please let me know if you see any issues.

2020-10-07 13:59 UTC, penguinwu approved these changes
LGTM

2020-10-07 13:59 UTC, merged