[WIP]Cleanup scratch register
v8-riscv/v8 pull request #420
Opened 2021-02-04 08:02 UTC by luyahan

2021-02-04 13:47 UTC, fw-brice commented
Can you explain why t6 is removed from the set of scratch registers if it is still needed in several places for a scratch register? Doesn't that make the management of it more difficult?

2021-02-05 04:36 UTC, luyahan commented
> Can you explain why t6 is removed from the set of scratch registers if it is still needed in several places for a scratch register? Doesn't that make the management of it more difficult?

@qjivy wang to fixed t6 as the rs1 of jalr.So we can know where jump from when occurs segment error.

2021-02-05 06:23 UTC, qjivy commented
> Can you explain why t6 is removed from the set of scratch registers if it is still needed in several places for a scratch register? Doesn't that make the management of it more difficult?

One observation is that MIPS only uses t9 for jalr instruction (call function or jump to a code object). With this usage convention, if we have a failure site in the JITed code, we can simply regards the contents of t9 at this spot as the final jalr destination. This would be help debugging in a sense.

According to the above notion, we want to change all the jalr's rs register to t6. #420 tries to remove t6 from the MacroAssembler's scratch register list and use it for this special purpose. Avoiding to use t6 as a scratch register would help to reserve its value (not to be clobbered by instructions after the final jalr). It's a tiny improve for debugging. 

Please let us know if you have any ideas about this change. Perhaps it's better to firstly make a proposal next time.

2021-02-05 14:48 UTC, fw-brice commented
Please check the precheck and resolve formatting issues to avoid problems upstreaming. I'll do it this time.

2021-02-05 14:56 UTC, fw-brice requested changes
Just two changes to the comments to match the changed registers.

2021-02-05 14:56 UTC, fw-brice commented on src/codegen/riscv64/assembler-riscv64.cc
> +        auipc(t6, Hi20);  // Read PC + Hi20 into t5.
The comment should say "t6".

2021-02-05 14:56 UTC, fw-brice commented on src/codegen/riscv64/macro-assembler-riscv64.cc
> +    // extract exponent value of the source floating-point to t6
Comment should say "scratch" instead of "t6".

2021-02-05 21:20 UTC, fw-brice commented
Merged

2021-02-05 21:20 UTC, closed without merging